name: Clean PDF Metadata

on:
  workflow_dispatch:
  push:
    paths:
      - "pdfs/*.pdf"

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Install ExifTool
        run: |
          sudo apt-get update
          sudo apt-get install -y libimage-exiftool-perl

      - name: Clean PDFs
        run: |
          mkdir -p cleaned

          for file in pdfs/*.pdf; do
            [ -f "$file" ] || continue

            filename=$(basename "$file")

            exiftool \
              -all= \
              -o "cleaned/$filename" \
              "$file"
          done

      - name: Save cleaned PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add cleaned/

          if git diff --cached --quiet; then
            echo "No cleaned files to commit"
          else
            git commit -m "Clean PDF metadata"
            git push
          fi
